# Generated by Django 3.2.18 on 2023-02-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hfhdhm', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
